# Generated by Django 5.0.6 on 2024-06-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mqttapp", "0002_deprtment"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Deprtment",
        ),
    ]
